/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AccordionItem } from "./components/accordion/accordion";
export { AccordionItem } from "./components/accordion/accordion";
export namespace Components {
    /**
     * @component sg-accordion
     * @description A collapsible accordion component.
     */
    interface SgAccordion {
        /**
          * Bordered style
          * @default true
         */
        "bordered": boolean;
        /**
          * Currently expanded panel(s)
          * @default []
         */
        "expanded": string | string[];
        /**
          * Icon position
          * @default 'right'
         */
        "iconPosition": 'left' | 'right';
        /**
          * Accordion items
          * @default []
         */
        "items": AccordionItem[] | string;
        /**
          * Allow multiple panels open
          * @default false
         */
        "multiple": boolean;
        /**
          * Size variant
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
    }
}
export interface SgAccordionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSgAccordionElement;
}
declare global {
    interface HTMLSgAccordionElementEventMap {
        "sgToggle": { id: string; expanded: boolean };
    }
    /**
     * @component sg-accordion
     * @description A collapsible accordion component.
     */
    interface HTMLSgAccordionElement extends Components.SgAccordion, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSgAccordionElementEventMap>(type: K, listener: (this: HTMLSgAccordionElement, ev: SgAccordionCustomEvent<HTMLSgAccordionElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSgAccordionElementEventMap>(type: K, listener: (this: HTMLSgAccordionElement, ev: SgAccordionCustomEvent<HTMLSgAccordionElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSgAccordionElement: {
        prototype: HTMLSgAccordionElement;
        new (): HTMLSgAccordionElement;
    };
    interface HTMLElementTagNameMap {
        "sg-accordion": HTMLSgAccordionElement;
    }
}
declare namespace LocalJSX {
    /**
     * @component sg-accordion
     * @description A collapsible accordion component.
     */
    interface SgAccordion {
        /**
          * Bordered style
          * @default true
         */
        "bordered"?: boolean;
        /**
          * Currently expanded panel(s)
          * @default []
         */
        "expanded"?: string | string[];
        /**
          * Icon position
          * @default 'right'
         */
        "iconPosition"?: 'left' | 'right';
        /**
          * Accordion items
          * @default []
         */
        "items"?: AccordionItem[] | string;
        /**
          * Allow multiple panels open
          * @default false
         */
        "multiple"?: boolean;
        /**
          * Emitted when panel is toggled
         */
        "onSgToggle"?: (event: SgAccordionCustomEvent<{ id: string; expanded: boolean }>) => void;
        /**
          * Size variant
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
    }
    interface IntrinsicElements {
        "sg-accordion": SgAccordion;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @component sg-accordion
             * @description A collapsible accordion component.
             */
            "sg-accordion": LocalJSX.SgAccordion & JSXBase.HTMLAttributes<HTMLSgAccordionElement>;
        }
    }
}
