
import * as d from './proxies';

export const DIRECTIVES = [
  d.SgAccordion,
  d.SgAlert,
  d.SgArticleEditor,
  d.SgAvatar,
  d.SgBadge,
  d.SgBreadcrumb,
  d.SgBreadcrumbItem,
  d.SgButton,
  d.SgCard,
  d.SgCheckbox,
  d.SgContextMenu,
  d.SgDatagrid,
  d.SgDatePicker,
  d.SgDropdown,
  d.SgFormSection,
  d.SgIcon,
  d.SgInfoField,
  d.SgInput,
  d.SgModal,
  d.SgOption,
  d.SgOptionGroup,
  d.SgProgress,
  d.SgRadio,
  d.SgSearchBox,
  d.SgSelect,
  d.SgSkeleton,
  d.SgStatsCard,
  d.SgSwitch,
  d.SgTabs,
  d.SgThemeToggle,
  d.SgToast,
  d.SgTooltip
];
