/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DatagridColumn, DatagridPagination, DatagridSort } from "./components/datagrid/datagrid";
export { DatagridColumn, DatagridPagination, DatagridSort } from "./components/datagrid/datagrid";
export namespace Components {
    /**
     * @component sg-datagrid
     * @description A powerful datagrid component with sorting, pagination, and row selection.
     * @example ```html
     * <sg-datagrid
     *   columns='[{"key":"name","header":"Name","sortable":true},{"key":"email","header":"Email"}]'
     *   data='[{"name":"John","email":"john@example.com"}]'
     *   selectable
     *   paginated
     *   page-size="10"
     * ></sg-datagrid>
     * ```
     */
    interface SgDatagrid {
        /**
          * Bordered style
          * @default false
         */
        "bordered": boolean;
        /**
          * Clear selection
         */
        "clearSelection": () => Promise<void>;
        /**
          * Column definitions
          * @default []
         */
        "columns": DatagridColumn[] | string;
        /**
          * Compact mode
          * @default false
         */
        "compact": boolean;
        /**
          * Data rows
          * @default []
         */
        "data": any[] | string;
        /**
          * Empty state message
          * @default 'No hay datos disponibles'
         */
        "emptyMessage": string;
        /**
          * Get selected rows
         */
        "getSelectedRows": () => Promise<any[]>;
        /**
          * Go to specific page
         */
        "goToPage": (page: number) => Promise<void>;
        /**
          * Hoverable rows
          * @default true
         */
        "hoverable": boolean;
        /**
          * Show loading state
          * @default false
         */
        "loading": boolean;
        /**
          * Enable multi-row selection
          * @default true
         */
        "multiSelect": boolean;
        /**
          * Items per page
          * @default 10
         */
        "pageSize": number;
        /**
          * Available page sizes
          * @default [10, 25, 50, 100]
         */
        "pageSizes": number[] | string;
        /**
          * Enable pagination
          * @default false
         */
        "paginated": boolean;
        /**
          * Select all rows
         */
        "selectAll": () => Promise<void>;
        /**
          * Enable row selection
          * @default false
         */
        "selectable": boolean;
        /**
          * Sticky header
          * @default false
         */
        "stickyHeader": boolean;
        /**
          * Striped rows
          * @default false
         */
        "striped": boolean;
    }
}
export interface SgDatagridCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSgDatagridElement;
}
declare global {
    interface HTMLSgDatagridElementEventMap {
        "sgSelect": { selected: any[]; indices: number[] };
        "sgSort": DatagridSort | null;
        "sgPageChange": DatagridPagination;
        "sgRowClick": { row: any; index: number };
    }
    /**
     * @component sg-datagrid
     * @description A powerful datagrid component with sorting, pagination, and row selection.
     * @example ```html
     * <sg-datagrid
     *   columns='[{"key":"name","header":"Name","sortable":true},{"key":"email","header":"Email"}]'
     *   data='[{"name":"John","email":"john@example.com"}]'
     *   selectable
     *   paginated
     *   page-size="10"
     * ></sg-datagrid>
     * ```
     */
    interface HTMLSgDatagridElement extends Components.SgDatagrid, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSgDatagridElementEventMap>(type: K, listener: (this: HTMLSgDatagridElement, ev: SgDatagridCustomEvent<HTMLSgDatagridElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSgDatagridElementEventMap>(type: K, listener: (this: HTMLSgDatagridElement, ev: SgDatagridCustomEvent<HTMLSgDatagridElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSgDatagridElement: {
        prototype: HTMLSgDatagridElement;
        new (): HTMLSgDatagridElement;
    };
    interface HTMLElementTagNameMap {
        "sg-datagrid": HTMLSgDatagridElement;
    }
}
declare namespace LocalJSX {
    /**
     * @component sg-datagrid
     * @description A powerful datagrid component with sorting, pagination, and row selection.
     * @example ```html
     * <sg-datagrid
     *   columns='[{"key":"name","header":"Name","sortable":true},{"key":"email","header":"Email"}]'
     *   data='[{"name":"John","email":"john@example.com"}]'
     *   selectable
     *   paginated
     *   page-size="10"
     * ></sg-datagrid>
     * ```
     */
    interface SgDatagrid {
        /**
          * Bordered style
          * @default false
         */
        "bordered"?: boolean;
        /**
          * Column definitions
          * @default []
         */
        "columns"?: DatagridColumn[] | string;
        /**
          * Compact mode
          * @default false
         */
        "compact"?: boolean;
        /**
          * Data rows
          * @default []
         */
        "data"?: any[] | string;
        /**
          * Empty state message
          * @default 'No hay datos disponibles'
         */
        "emptyMessage"?: string;
        /**
          * Hoverable rows
          * @default true
         */
        "hoverable"?: boolean;
        /**
          * Show loading state
          * @default false
         */
        "loading"?: boolean;
        /**
          * Enable multi-row selection
          * @default true
         */
        "multiSelect"?: boolean;
        /**
          * Emitted when page changes
         */
        "onSgPageChange"?: (event: SgDatagridCustomEvent<DatagridPagination>) => void;
        /**
          * Emitted when a row is clicked
         */
        "onSgRowClick"?: (event: SgDatagridCustomEvent<{ row: any; index: number }>) => void;
        /**
          * Emitted when row selection changes
         */
        "onSgSelect"?: (event: SgDatagridCustomEvent<{ selected: any[]; indices: number[] }>) => void;
        /**
          * Emitted when sort changes
         */
        "onSgSort"?: (event: SgDatagridCustomEvent<DatagridSort | null>) => void;
        /**
          * Items per page
          * @default 10
         */
        "pageSize"?: number;
        /**
          * Available page sizes
          * @default [10, 25, 50, 100]
         */
        "pageSizes"?: number[] | string;
        /**
          * Enable pagination
          * @default false
         */
        "paginated"?: boolean;
        /**
          * Enable row selection
          * @default false
         */
        "selectable"?: boolean;
        /**
          * Sticky header
          * @default false
         */
        "stickyHeader"?: boolean;
        /**
          * Striped rows
          * @default false
         */
        "striped"?: boolean;
    }
    interface IntrinsicElements {
        "sg-datagrid": SgDatagrid;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @component sg-datagrid
             * @description A powerful datagrid component with sorting, pagination, and row selection.
             * @example ```html
             * <sg-datagrid
             *   columns='[{"key":"name","header":"Name","sortable":true},{"key":"email","header":"Email"}]'
             *   data='[{"name":"John","email":"john@example.com"}]'
             *   selectable
             *   paginated
             *   page-size="10"
             * ></sg-datagrid>
             * ```
             */
            "sg-datagrid": LocalJSX.SgDatagrid & JSXBase.HTMLAttributes<HTMLSgDatagridElement>;
        }
    }
}
