/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TabItem } from "./components/tabs/tabs";
export { TabItem } from "./components/tabs/tabs";
export namespace Components {
    /**
     * @component sg-tabs
     * @description A flexible tabs component with horizontal/vertical orientation and multiple variants.
     * @example ```html
     * <sg-tabs
     *   tabs='[{"id":"tab1","label":"General"},{"id":"tab2","label":"Settings"}]'
     *   active-tab="tab1"
     * >
     *   <div slot="tab1">General content</div>
     *   <div slot="tab2">Settings content</div>
     * </sg-tabs>
     * ```
     */
    interface SgTabs {
        /**
          * Currently active tab ID
         */
        "activeTab"?: string;
        /**
          * Full width tabs
          * @default false
         */
        "fullWidth": boolean;
        /**
          * Get active tab info
         */
        "getActiveTab": () => Promise<TabItem | undefined>;
        /**
          * Enable keyboard navigation
          * @default true
         */
        "keyboard": boolean;
        /**
          * Lazy load tab content
          * @default false
         */
        "lazy": boolean;
        /**
          * Tabs orientation
          * @default 'horizontal'
         */
        "orientation": 'horizontal' | 'vertical';
        /**
          * Select a tab by ID
         */
        "selectTab": (tabId: string) => Promise<void>;
        /**
          * Size
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * Tab items configuration
          * @default []
         */
        "tabs": TabItem[] | string;
        /**
          * Visual variant
          * @default 'default'
         */
        "variant": 'default' | 'pills' | 'underline' | 'bordered';
    }
}
export interface SgTabsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSgTabsElement;
}
declare global {
    interface HTMLSgTabsElementEventMap {
        "sgTabChange": { tabId: string; tab: TabItem };
    }
    /**
     * @component sg-tabs
     * @description A flexible tabs component with horizontal/vertical orientation and multiple variants.
     * @example ```html
     * <sg-tabs
     *   tabs='[{"id":"tab1","label":"General"},{"id":"tab2","label":"Settings"}]'
     *   active-tab="tab1"
     * >
     *   <div slot="tab1">General content</div>
     *   <div slot="tab2">Settings content</div>
     * </sg-tabs>
     * ```
     */
    interface HTMLSgTabsElement extends Components.SgTabs, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSgTabsElementEventMap>(type: K, listener: (this: HTMLSgTabsElement, ev: SgTabsCustomEvent<HTMLSgTabsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSgTabsElementEventMap>(type: K, listener: (this: HTMLSgTabsElement, ev: SgTabsCustomEvent<HTMLSgTabsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSgTabsElement: {
        prototype: HTMLSgTabsElement;
        new (): HTMLSgTabsElement;
    };
    interface HTMLElementTagNameMap {
        "sg-tabs": HTMLSgTabsElement;
    }
}
declare namespace LocalJSX {
    /**
     * @component sg-tabs
     * @description A flexible tabs component with horizontal/vertical orientation and multiple variants.
     * @example ```html
     * <sg-tabs
     *   tabs='[{"id":"tab1","label":"General"},{"id":"tab2","label":"Settings"}]'
     *   active-tab="tab1"
     * >
     *   <div slot="tab1">General content</div>
     *   <div slot="tab2">Settings content</div>
     * </sg-tabs>
     * ```
     */
    interface SgTabs {
        /**
          * Currently active tab ID
         */
        "activeTab"?: string;
        /**
          * Full width tabs
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * Enable keyboard navigation
          * @default true
         */
        "keyboard"?: boolean;
        /**
          * Lazy load tab content
          * @default false
         */
        "lazy"?: boolean;
        /**
          * Emitted when active tab changes
         */
        "onSgTabChange"?: (event: SgTabsCustomEvent<{ tabId: string; tab: TabItem }>) => void;
        /**
          * Tabs orientation
          * @default 'horizontal'
         */
        "orientation"?: 'horizontal' | 'vertical';
        /**
          * Size
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * Tab items configuration
          * @default []
         */
        "tabs"?: TabItem[] | string;
        /**
          * Visual variant
          * @default 'default'
         */
        "variant"?: 'default' | 'pills' | 'underline' | 'bordered';
    }
    interface IntrinsicElements {
        "sg-tabs": SgTabs;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @component sg-tabs
             * @description A flexible tabs component with horizontal/vertical orientation and multiple variants.
             * @example ```html
             * <sg-tabs
             *   tabs='[{"id":"tab1","label":"General"},{"id":"tab2","label":"Settings"}]'
             *   active-tab="tab1"
             * >
             *   <div slot="tab1">General content</div>
             *   <div slot="tab2">Settings content</div>
             * </sg-tabs>
             * ```
             */
            "sg-tabs": LocalJSX.SgTabs & JSXBase.HTMLAttributes<HTMLSgTabsElement>;
        }
    }
}
