/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * @component sg-switch
     * @description A toggle switch component.
     */
    interface SgSwitch {
        /**
          * Whether the switch is on
          * @default false
         */
        "checked": boolean;
        /**
          * Color when checked
          * @default 'primary'
         */
        "color": 'primary' | 'success' | 'warning' | 'error';
        /**
          * Whether the switch is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Label position
          * @default 'right'
         */
        "labelPosition": 'left' | 'right';
        /**
          * Switch name for form submission
         */
        "name"?: string;
        /**
          * Text when off
          * @default 'OFF'
         */
        "offText": string;
        /**
          * Text when on
          * @default 'ON'
         */
        "onText": string;
        /**
          * Show on/off text inside switch
          * @default false
         */
        "showText": boolean;
        /**
          * Size variant
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
    }
}
export interface SgSwitchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSgSwitchElement;
}
declare global {
    interface HTMLSgSwitchElementEventMap {
        "sgChange": { checked: boolean };
    }
    /**
     * @component sg-switch
     * @description A toggle switch component.
     */
    interface HTMLSgSwitchElement extends Components.SgSwitch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSgSwitchElementEventMap>(type: K, listener: (this: HTMLSgSwitchElement, ev: SgSwitchCustomEvent<HTMLSgSwitchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSgSwitchElementEventMap>(type: K, listener: (this: HTMLSgSwitchElement, ev: SgSwitchCustomEvent<HTMLSgSwitchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSgSwitchElement: {
        prototype: HTMLSgSwitchElement;
        new (): HTMLSgSwitchElement;
    };
    interface HTMLElementTagNameMap {
        "sg-switch": HTMLSgSwitchElement;
    }
}
declare namespace LocalJSX {
    /**
     * @component sg-switch
     * @description A toggle switch component.
     */
    interface SgSwitch {
        /**
          * Whether the switch is on
          * @default false
         */
        "checked"?: boolean;
        /**
          * Color when checked
          * @default 'primary'
         */
        "color"?: 'primary' | 'success' | 'warning' | 'error';
        /**
          * Whether the switch is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Label position
          * @default 'right'
         */
        "labelPosition"?: 'left' | 'right';
        /**
          * Switch name for form submission
         */
        "name"?: string;
        /**
          * Text when off
          * @default 'OFF'
         */
        "offText"?: string;
        /**
          * Emitted when switch state changes
         */
        "onSgChange"?: (event: SgSwitchCustomEvent<{ checked: boolean }>) => void;
        /**
          * Text when on
          * @default 'ON'
         */
        "onText"?: string;
        /**
          * Show on/off text inside switch
          * @default false
         */
        "showText"?: boolean;
        /**
          * Size variant
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
    }
    interface IntrinsicElements {
        "sg-switch": SgSwitch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @component sg-switch
             * @description A toggle switch component.
             */
            "sg-switch": LocalJSX.SgSwitch & JSXBase.HTMLAttributes<HTMLSgSwitchElement>;
        }
    }
}
