/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RadioOption } from "./components/radio/radio";
export { RadioOption } from "./components/radio/radio";
export namespace Components {
    /**
     * @component sg-radio
     * @description A radio button group component.
     */
    interface SgRadio {
        /**
          * Color variant
          * @default 'primary'
         */
        "color": 'primary' | 'success' | 'warning' | 'error';
        /**
          * Whether the entire group is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Radio group name
          * @default ''
         */
        "name": string;
        /**
          * Options array
          * @default []
         */
        "options": RadioOption[] | string;
        /**
          * Orientation
          * @default 'vertical'
         */
        "orientation": 'horizontal' | 'vertical';
        /**
          * Size variant
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * Currently selected value
         */
        "value"?: string;
    }
}
export interface SgRadioCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSgRadioElement;
}
declare global {
    interface HTMLSgRadioElementEventMap {
        "sgChange": { value: string };
    }
    /**
     * @component sg-radio
     * @description A radio button group component.
     */
    interface HTMLSgRadioElement extends Components.SgRadio, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSgRadioElementEventMap>(type: K, listener: (this: HTMLSgRadioElement, ev: SgRadioCustomEvent<HTMLSgRadioElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSgRadioElementEventMap>(type: K, listener: (this: HTMLSgRadioElement, ev: SgRadioCustomEvent<HTMLSgRadioElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSgRadioElement: {
        prototype: HTMLSgRadioElement;
        new (): HTMLSgRadioElement;
    };
    interface HTMLElementTagNameMap {
        "sg-radio": HTMLSgRadioElement;
    }
}
declare namespace LocalJSX {
    /**
     * @component sg-radio
     * @description A radio button group component.
     */
    interface SgRadio {
        /**
          * Color variant
          * @default 'primary'
         */
        "color"?: 'primary' | 'success' | 'warning' | 'error';
        /**
          * Whether the entire group is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Radio group name
          * @default ''
         */
        "name"?: string;
        /**
          * Emitted when selection changes
         */
        "onSgChange"?: (event: SgRadioCustomEvent<{ value: string }>) => void;
        /**
          * Options array
          * @default []
         */
        "options"?: RadioOption[] | string;
        /**
          * Orientation
          * @default 'vertical'
         */
        "orientation"?: 'horizontal' | 'vertical';
        /**
          * Size variant
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * Currently selected value
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "sg-radio": SgRadio;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @component sg-radio
             * @description A radio button group component.
             */
            "sg-radio": LocalJSX.SgRadio & JSXBase.HTMLAttributes<HTMLSgRadioElement>;
        }
    }
}
