/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * @component sg-checkbox
     * @description A customizable checkbox component with label support.
     */
    interface SgCheckbox {
        /**
          * Whether the checkbox is checked
          * @default false
         */
        "checked": boolean;
        /**
          * Color variant
          * @default 'primary'
         */
        "color": 'primary' | 'success' | 'warning' | 'error';
        /**
          * Whether the checkbox is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Error state
          * @default false
         */
        "error": boolean;
        /**
          * Helper/error text
         */
        "helperText"?: string;
        /**
          * Indeterminate state (partially checked)
          * @default false
         */
        "indeterminate": boolean;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Checkbox name for form submission
         */
        "name"?: string;
        /**
          * Size variant
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * Checkbox value
         */
        "value"?: string;
    }
}
export interface SgCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSgCheckboxElement;
}
declare global {
    interface HTMLSgCheckboxElementEventMap {
        "sgChange": { checked: boolean; value?: string };
    }
    /**
     * @component sg-checkbox
     * @description A customizable checkbox component with label support.
     */
    interface HTMLSgCheckboxElement extends Components.SgCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSgCheckboxElementEventMap>(type: K, listener: (this: HTMLSgCheckboxElement, ev: SgCheckboxCustomEvent<HTMLSgCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSgCheckboxElementEventMap>(type: K, listener: (this: HTMLSgCheckboxElement, ev: SgCheckboxCustomEvent<HTMLSgCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSgCheckboxElement: {
        prototype: HTMLSgCheckboxElement;
        new (): HTMLSgCheckboxElement;
    };
    interface HTMLElementTagNameMap {
        "sg-checkbox": HTMLSgCheckboxElement;
    }
}
declare namespace LocalJSX {
    /**
     * @component sg-checkbox
     * @description A customizable checkbox component with label support.
     */
    interface SgCheckbox {
        /**
          * Whether the checkbox is checked
          * @default false
         */
        "checked"?: boolean;
        /**
          * Color variant
          * @default 'primary'
         */
        "color"?: 'primary' | 'success' | 'warning' | 'error';
        /**
          * Whether the checkbox is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error state
          * @default false
         */
        "error"?: boolean;
        /**
          * Helper/error text
         */
        "helperText"?: string;
        /**
          * Indeterminate state (partially checked)
          * @default false
         */
        "indeterminate"?: boolean;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Checkbox name for form submission
         */
        "name"?: string;
        /**
          * Emitted when checked state changes
         */
        "onSgChange"?: (event: SgCheckboxCustomEvent<{ checked: boolean; value?: string }>) => void;
        /**
          * Size variant
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * Checkbox value
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "sg-checkbox": SgCheckbox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @component sg-checkbox
             * @description A customizable checkbox component with label support.
             */
            "sg-checkbox": LocalJSX.SgCheckbox & JSXBase.HTMLAttributes<HTMLSgCheckboxElement>;
        }
    }
}
