/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * @component sg-progress
     * @description A progress indicator component (linear and circular).
     */
    interface SgProgress {
        /**
          * Animated stripes
          * @default false
         */
        "animated": boolean;
        /**
          * Color variant
          * @default 'primary'
         */
        "color": 'primary' | 'success' | 'warning' | 'error';
        /**
          * Indeterminate state (animated)
          * @default false
         */
        "indeterminate": boolean;
        /**
          * Custom label
         */
        "label"?: string;
        /**
          * Maximum value
          * @default 100
         */
        "max": number;
        /**
          * Show percentage label
          * @default false
         */
        "showLabel": boolean;
        /**
          * Size variant
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * Striped pattern (linear only)
          * @default false
         */
        "striped": boolean;
        /**
          * Progress type
          * @default 'linear'
         */
        "type": 'linear' | 'circular';
        /**
          * Current progress value (0-100)
          * @default 0
         */
        "value": number;
    }
}
declare global {
    /**
     * @component sg-progress
     * @description A progress indicator component (linear and circular).
     */
    interface HTMLSgProgressElement extends Components.SgProgress, HTMLStencilElement {
    }
    var HTMLSgProgressElement: {
        prototype: HTMLSgProgressElement;
        new (): HTMLSgProgressElement;
    };
    interface HTMLElementTagNameMap {
        "sg-progress": HTMLSgProgressElement;
    }
}
declare namespace LocalJSX {
    /**
     * @component sg-progress
     * @description A progress indicator component (linear and circular).
     */
    interface SgProgress {
        /**
          * Animated stripes
          * @default false
         */
        "animated"?: boolean;
        /**
          * Color variant
          * @default 'primary'
         */
        "color"?: 'primary' | 'success' | 'warning' | 'error';
        /**
          * Indeterminate state (animated)
          * @default false
         */
        "indeterminate"?: boolean;
        /**
          * Custom label
         */
        "label"?: string;
        /**
          * Maximum value
          * @default 100
         */
        "max"?: number;
        /**
          * Show percentage label
          * @default false
         */
        "showLabel"?: boolean;
        /**
          * Size variant
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * Striped pattern (linear only)
          * @default false
         */
        "striped"?: boolean;
        /**
          * Progress type
          * @default 'linear'
         */
        "type"?: 'linear' | 'circular';
        /**
          * Current progress value (0-100)
          * @default 0
         */
        "value"?: number;
    }
    interface IntrinsicElements {
        "sg-progress": SgProgress;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @component sg-progress
             * @description A progress indicator component (linear and circular).
             */
            "sg-progress": LocalJSX.SgProgress & JSXBase.HTMLAttributes<HTMLSgProgressElement>;
        }
    }
}
