/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { SelectOption, SelectSize, SelectVariant, ValidationState } from './components/select/select';
export { SelectOption, SelectSize, SelectVariant, ValidationState } from './components/select/select';
export namespace Components {
  /**
   * @component sg-option
   * @description Option element for sg-select component
   * @example <sg-select label="Choose">
   *   <sg-option value="1">Option 1</sg-option>
   *   <sg-option value="2" disabled>Option 2 (disabled)</sg-option>
   *   <sg-option value="3" icon="mdi:star">Option 3 with icon</sg-option>
   * </sg-select>
   */
  interface SgOption {
    /**
     * Description text
     */
    description?: string;
    /**
     * Whether option is disabled
     * @default false
     */
    disabled: boolean;
    /**
     * Icon name
     */
    icon?: string;
    /**
     * Option value
     */
    value: string;
  }
  /**
   * @component sg-option-group
   * @description Group of options for sg-select component
   * @example <sg-select label="Choose">
   *   <sg-option-group label="Group A">
   *     <sg-option value="1">Option 1</sg-option>
   *     <sg-option value="2">Option 2</sg-option>
   *   </sg-option-group>
   *   <sg-option-group label="Group B">
   *     <sg-option value="3">Option 3</sg-option>
   *   </sg-option-group>
   * </sg-select>
   */
  interface SgOptionGroup {
    /**
     * Whether all options in group are disabled
     * @default false
     */
    disabled: boolean;
    /**
     * Group label
     */
    label: string;
  }
  /**
   * @component sg-select
   * @description Advanced select/combobox component with search, multi-select, async loading, and more.
   * @example <!-- Basic usage -->
   * <sg-select label="Country" placeholder="Select a country">
   *   <sg-option value="us">United States</sg-option>
   *   <sg-option value="uk">United Kingdom</sg-option>
   *   <sg-option value="es">Spain</sg-option>
   * </sg-select>
   * <!-- With search -->
   * <sg-select label="Search countries" searchable>
   *   <sg-option value="us">United States</sg-option>
   *   <sg-option value="uk">United Kingdom</sg-option>
   * </sg-select>
   * <!-- Multi-select -->
   * <sg-select label="Select tags" multiple>
   *   <sg-option value="react">React</sg-option>
   *   <sg-option value="vue">Vue</sg-option>
   *   <sg-option value="angular">Angular</sg-option>
   * </sg-select>
   * @fires sgChange - Emitted when selection changes
   * @fires sgSearch - Emitted when search query changes (for async loading)
   * @fires sgOpen - Emitted when dropdown opens
   * @fires sgClose - Emitted when dropdown closes
   */
  interface SgSelect {
    /**
     * Enable async loading (use sgSearch event)
     * @default false
     */
    async: boolean;
    clear: () => Promise<void>;
    /**
     * Allow clearing selection
     * @default false
     */
    clearable: boolean;
    close: () => Promise<void>;
    /**
     * Close dropdown after selection (single select)
     * @default true
     */
    closeOnSelect: boolean;
    /**
     * Allow creating new options
     * @default false
     */
    creatable: boolean;
    /**
     * Create option text template (use {query} placeholder)
     * @default 'Create "{query}"'
     */
    createText: string;
    /**
     * Disabled state
     * @default false
     */
    disabled: boolean;
    /**
     * Error message
     */
    errorMessage?: string;
    /**
     * Helper text below the select
     */
    helperText?: string;
    /**
     * Label text
     */
    label?: string;
    /**
     * Show loading indicator
     * @default false
     */
    loading: boolean;
    /**
     * Loading text
     * @default 'Loading...'
     */
    loadingText: string;
    /**
     * Maximum selections for multi-select
     */
    maxSelections?: number;
    /**
     * Allow multiple selections
     * @default false
     */
    multiple: boolean;
    /**
     * No results text
     * @default 'No results found'
     */
    noResultsText: string;
    open: () => Promise<void>;
    /**
     * Options passed as array (alternative to slots)
     */
    options?: SelectOption[] | string;
    /**
     * Placeholder text
     */
    placeholder?: string;
    /**
     * Required field
     * @default false
     */
    required: boolean;
    /**
     * Search debounce delay in ms
     * @default 300
     */
    searchDelay: number;
    /**
     * Enable search/filter functionality
     * @default false
     */
    searchable: boolean;
    /**
     * Size variant
     * @default 'md'
     */
    size: SelectSize;
    toggle: () => Promise<void>;
    /**
     * Validation state
     * @default 'default'
     */
    validationState: ValidationState;
    /**
     * Current value (single select) or values (multi-select as JSON array)
     */
    value?: string;
    /**
     * Array of selected values for multi-select
     * @default []
     */
    values: string[];
    /**
     * Visual variant
     * @default 'default'
     */
    variant: SelectVariant;
  }
}
export interface SgSelectCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLSgSelectElement;
}
declare global {
  /**
   * @component sg-option
   * @description Option element for sg-select component
   * @example <sg-select label="Choose">
   *   <sg-option value="1">Option 1</sg-option>
   *   <sg-option value="2" disabled>Option 2 (disabled)</sg-option>
   *   <sg-option value="3" icon="mdi:star">Option 3 with icon</sg-option>
   * </sg-select>
   */
  interface HTMLSgOptionElement extends Components.SgOption, HTMLStencilElement {}
  var HTMLSgOptionElement: {
    prototype: HTMLSgOptionElement;
    new (): HTMLSgOptionElement;
  };
  /**
   * @component sg-option-group
   * @description Group of options for sg-select component
   * @example <sg-select label="Choose">
   *   <sg-option-group label="Group A">
   *     <sg-option value="1">Option 1</sg-option>
   *     <sg-option value="2">Option 2</sg-option>
   *   </sg-option-group>
   *   <sg-option-group label="Group B">
   *     <sg-option value="3">Option 3</sg-option>
   *   </sg-option-group>
   * </sg-select>
   */
  interface HTMLSgOptionGroupElement extends Components.SgOptionGroup, HTMLStencilElement {}
  var HTMLSgOptionGroupElement: {
    prototype: HTMLSgOptionGroupElement;
    new (): HTMLSgOptionGroupElement;
  };
  interface HTMLSgSelectElementEventMap {
    sgChange: {
      value: string | string[];
      option?: { value: string; label: string; disabled?: boolean; group?: string; icon?: string; description?: string; data?: unknown };
    };
    sgSearch: { query: string };
    sgOpen: void;
    sgClose: void;
    sgCreate: { value: string };
  }
  /**
   * @component sg-select
   * @description Advanced select/combobox component with search, multi-select, async loading, and more.
   * @example <!-- Basic usage -->
   * <sg-select label="Country" placeholder="Select a country">
   *   <sg-option value="us">United States</sg-option>
   *   <sg-option value="uk">United Kingdom</sg-option>
   *   <sg-option value="es">Spain</sg-option>
   * </sg-select>
   * <!-- With search -->
   * <sg-select label="Search countries" searchable>
   *   <sg-option value="us">United States</sg-option>
   *   <sg-option value="uk">United Kingdom</sg-option>
   * </sg-select>
   * <!-- Multi-select -->
   * <sg-select label="Select tags" multiple>
   *   <sg-option value="react">React</sg-option>
   *   <sg-option value="vue">Vue</sg-option>
   *   <sg-option value="angular">Angular</sg-option>
   * </sg-select>
   * @fires sgChange - Emitted when selection changes
   * @fires sgSearch - Emitted when search query changes (for async loading)
   * @fires sgOpen - Emitted when dropdown opens
   * @fires sgClose - Emitted when dropdown closes
   */
  interface HTMLSgSelectElement extends Components.SgSelect, HTMLStencilElement {
    addEventListener<K extends keyof HTMLSgSelectElementEventMap>(
      type: K,
      listener: (this: HTMLSgSelectElement, ev: SgSelectCustomEvent<HTMLSgSelectElementEventMap[K]>) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof HTMLSgSelectElementEventMap>(
      type: K,
      listener: (this: HTMLSgSelectElement, ev: SgSelectCustomEvent<HTMLSgSelectElementEventMap[K]>) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
  }
  var HTMLSgSelectElement: {
    prototype: HTMLSgSelectElement;
    new (): HTMLSgSelectElement;
  };
  interface HTMLElementTagNameMap {
    'sg-option': HTMLSgOptionElement;
    'sg-option-group': HTMLSgOptionGroupElement;
    'sg-select': HTMLSgSelectElement;
  }
}
declare namespace LocalJSX {
  /**
   * @component sg-option
   * @description Option element for sg-select component
   * @example <sg-select label="Choose">
   *   <sg-option value="1">Option 1</sg-option>
   *   <sg-option value="2" disabled>Option 2 (disabled)</sg-option>
   *   <sg-option value="3" icon="mdi:star">Option 3 with icon</sg-option>
   * </sg-select>
   */
  interface SgOption {
    /**
     * Description text
     */
    description?: string;
    /**
     * Whether option is disabled
     * @default false
     */
    disabled?: boolean;
    /**
     * Icon name
     */
    icon?: string;
    /**
     * Option value
     */
    value: string;
  }
  /**
   * @component sg-option-group
   * @description Group of options for sg-select component
   * @example <sg-select label="Choose">
   *   <sg-option-group label="Group A">
   *     <sg-option value="1">Option 1</sg-option>
   *     <sg-option value="2">Option 2</sg-option>
   *   </sg-option-group>
   *   <sg-option-group label="Group B">
   *     <sg-option value="3">Option 3</sg-option>
   *   </sg-option-group>
   * </sg-select>
   */
  interface SgOptionGroup {
    /**
     * Whether all options in group are disabled
     * @default false
     */
    disabled?: boolean;
    /**
     * Group label
     */
    label: string;
  }
  /**
   * @component sg-select
   * @description Advanced select/combobox component with search, multi-select, async loading, and more.
   * @example <!-- Basic usage -->
   * <sg-select label="Country" placeholder="Select a country">
   *   <sg-option value="us">United States</sg-option>
   *   <sg-option value="uk">United Kingdom</sg-option>
   *   <sg-option value="es">Spain</sg-option>
   * </sg-select>
   * <!-- With search -->
   * <sg-select label="Search countries" searchable>
   *   <sg-option value="us">United States</sg-option>
   *   <sg-option value="uk">United Kingdom</sg-option>
   * </sg-select>
   * <!-- Multi-select -->
   * <sg-select label="Select tags" multiple>
   *   <sg-option value="react">React</sg-option>
   *   <sg-option value="vue">Vue</sg-option>
   *   <sg-option value="angular">Angular</sg-option>
   * </sg-select>
   * @fires sgChange - Emitted when selection changes
   * @fires sgSearch - Emitted when search query changes (for async loading)
   * @fires sgOpen - Emitted when dropdown opens
   * @fires sgClose - Emitted when dropdown closes
   */
  interface SgSelect {
    /**
     * Enable async loading (use sgSearch event)
     * @default false
     */
    async?: boolean;
    /**
     * Allow clearing selection
     * @default false
     */
    clearable?: boolean;
    /**
     * Close dropdown after selection (single select)
     * @default true
     */
    closeOnSelect?: boolean;
    /**
     * Allow creating new options
     * @default false
     */
    creatable?: boolean;
    /**
     * Create option text template (use {query} placeholder)
     * @default 'Create "{query}"'
     */
    createText?: string;
    /**
     * Disabled state
     * @default false
     */
    disabled?: boolean;
    /**
     * Error message
     */
    errorMessage?: string;
    /**
     * Helper text below the select
     */
    helperText?: string;
    /**
     * Label text
     */
    label?: string;
    /**
     * Show loading indicator
     * @default false
     */
    loading?: boolean;
    /**
     * Loading text
     * @default 'Loading...'
     */
    loadingText?: string;
    /**
     * Maximum selections for multi-select
     */
    maxSelections?: number;
    /**
     * Allow multiple selections
     * @default false
     */
    multiple?: boolean;
    /**
     * No results text
     * @default 'No results found'
     */
    noResultsText?: string;
    /**
     * Emitted when selection changes. The option property contains the selected option data.
     */
    onSgChange?: (
      event: SgSelectCustomEvent<{
        value: string | string[];
        option?: { value: string; label: string; disabled?: boolean; group?: string; icon?: string; description?: string; data?: unknown };
      }>,
    ) => void;
    onSgClose?: (event: SgSelectCustomEvent<void>) => void;
    onSgCreate?: (event: SgSelectCustomEvent<{ value: string }>) => void;
    onSgOpen?: (event: SgSelectCustomEvent<void>) => void;
    onSgSearch?: (event: SgSelectCustomEvent<{ query: string }>) => void;
    /**
     * Options passed as array (alternative to slots)
     */
    options?: SelectOption[] | string;
    /**
     * Placeholder text
     */
    placeholder?: string;
    /**
     * Required field
     * @default false
     */
    required?: boolean;
    /**
     * Search debounce delay in ms
     * @default 300
     */
    searchDelay?: number;
    /**
     * Enable search/filter functionality
     * @default false
     */
    searchable?: boolean;
    /**
     * Size variant
     * @default 'md'
     */
    size?: SelectSize;
    /**
     * Validation state
     * @default 'default'
     */
    validationState?: ValidationState;
    /**
     * Current value (single select) or values (multi-select as JSON array)
     */
    value?: string;
    /**
     * Array of selected values for multi-select
     * @default []
     */
    values?: string[];
    /**
     * Visual variant
     * @default 'default'
     */
    variant?: SelectVariant;
  }
  interface IntrinsicElements {
    'sg-option': SgOption;
    'sg-option-group': SgOptionGroup;
    'sg-select': SgSelect;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      /**
       * @component sg-option
       * @description Option element for sg-select component
       * @example <sg-select label="Choose">
       *   <sg-option value="1">Option 1</sg-option>
       *   <sg-option value="2" disabled>Option 2 (disabled)</sg-option>
       *   <sg-option value="3" icon="mdi:star">Option 3 with icon</sg-option>
       * </sg-select>
       */
      'sg-option': LocalJSX.SgOption & JSXBase.HTMLAttributes<HTMLSgOptionElement>;
      /**
       * @component sg-option-group
       * @description Group of options for sg-select component
       * @example <sg-select label="Choose">
       *   <sg-option-group label="Group A">
       *     <sg-option value="1">Option 1</sg-option>
       *     <sg-option value="2">Option 2</sg-option>
       *   </sg-option-group>
       *   <sg-option-group label="Group B">
       *     <sg-option value="3">Option 3</sg-option>
       *   </sg-option-group>
       * </sg-select>
       */
      'sg-option-group': LocalJSX.SgOptionGroup & JSXBase.HTMLAttributes<HTMLSgOptionGroupElement>;
      /**
       * @component sg-select
       * @description Advanced select/combobox component with search, multi-select, async loading, and more.
       * @example <!-- Basic usage -->
       * <sg-select label="Country" placeholder="Select a country">
       *   <sg-option value="us">United States</sg-option>
       *   <sg-option value="uk">United Kingdom</sg-option>
       *   <sg-option value="es">Spain</sg-option>
       * </sg-select>
       * <!-- With search -->
       * <sg-select label="Search countries" searchable>
       *   <sg-option value="us">United States</sg-option>
       *   <sg-option value="uk">United Kingdom</sg-option>
       * </sg-select>
       * <!-- Multi-select -->
       * <sg-select label="Select tags" multiple>
       *   <sg-option value="react">React</sg-option>
       *   <sg-option value="vue">Vue</sg-option>
       *   <sg-option value="angular">Angular</sg-option>
       * </sg-select>
       * @fires sgChange - Emitted when selection changes
       * @fires sgSearch - Emitted when search query changes (for async loading)
       * @fires sgOpen - Emitted when dropdown opens
       * @fires sgClose - Emitted when dropdown closes
       */
      'sg-select': LocalJSX.SgSelect & JSXBase.HTMLAttributes<HTMLSgSelectElement>;
    }
  }
}
